# tmp fix for https://github.com/zdharma-continuum/zinit/issues/418
# also need to ln this file to zinit actual path in nix store
[".local/share/zinit/polaris/man/man1/zinit.1"]
  type = "file"
  url = "https://raw.githubusercontent.com/zdharma-continuum/zinit/main/doc/zinit.1"
  refreshPeriod = "168h"

# broot theme
[".config/broot/skins/catppuccin-mocha-mauve.hjson"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/broot/refs/heads/main/themes/mocha/catppuccin-mocha-mauve.hjson"
  refreshPeriod = "168h"

# btop++ theme
[".config/btop/themes/catppuccin_mocha.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/btop/refs/heads/main/themes/catppuccin_mocha.theme"
  refreshPeriod = "168h"

# kitty theme
[".config/kitty/catppuccin_mocha.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/kitty/refs/heads/main/themes/mocha.conf"
  refreshPeriod = "168h"

# ZSH fast syntax highlighting
[".config/fsh/catppuccin-mocha.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/zsh-fsh/refs/heads/main/themes/catppuccin-mocha.ini"
  refreshPeriod = "168h"

# Yazi theme 
[".config/yazi/theme.toml"]
  type = "file"
  url = "https://github.com/catppuccin/yazi/raw/refs/heads/main/themes/mocha/catppuccin-mocha-mauve.toml"
  refreshPeriod = "168h"