# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_symbol = "/.../"

[gcloud]
disabled = true

[java]
style = 'red'
